# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: CopyFiles@2
  inputs:
    SourceFolder: 'https://github.com/aravinth-hcl-git/Testrepo1/blob/main/'
    Contents: '**'
    TargetFolder: 'https://aravinths0462@dev.azure.com/aravinths0462/aravinth-proj-test1/_git/aravinth-proj-test1'